const teams = [
  {id:1,name:"Mugiwara"},
  {id:2,name:"I Crackers"},
  {id:3,name:"Ananas Space"},
  {id:4,name:"Le bimbe del Grosso"},
  {id:5,name:"sxegier"},
  {id:6,name:"4mendi"},
  {id:7,name:"Big Ibos's"},
  {id:8,name:"Le Schiacciatine"},
  {id:9,name:"Quelli che hanno giocato prima"},
  {id:10,name:"Poiane"},
  {id:11,name:"È una squadra fantastica"},
  {id:12,name:"go go go go go"},
  {id:13,name:"Anca istan"},
  {id:14,name:"L'aura non c'è"},
  {id:15,name:"I Tarallini"},
  {id:16,name:"Albatros"},
  {id:17,name:"Corza e Foraggio"},
  {id:18,name:"Mobili Mobili Mobili"},
  {id:19,name:"Chi ama la patata batta le mani"},
  {id:20,name:"Ongin tonic"},
  {id:21,name:"3 tigri contro 3 tigri"},
  {id:22,name:"I pallalcolisti"},
  {id:23,name:"Un gintonezio per favore"},
  {id:24,name:"Una romanticheria per Mariotti"},
  {id:25,name:"Idee per il nome???"},
  {id:26,name:"Sesso & samba"},
  {id:27,name:"Gli umili"},
  {id:28,name:"Piace, sono pronti gli spiedini"},
  {id:29,name:"Piccionstriker"},
  {id:30,name:"I belli e la bestia"},
  {id:31,name:"Paolo c'è!"},
  {id:32,name:"Gigio team"},
  {id:33,name:"A i come lunga, e ee yeye si ripete"},
  {id:34,name:"Ogni volta che ci chiami una Guinness di rigore"},
  {id:35,name:"Sbronzi di Riace"},
  {id:36,name:"Chat GPT non aiuta"},
  {id:37,name:"Not your business"},
  {id:38,name:"Vertical isso"},
  {id:39,name:"Thevolleisti"},
  {id:40,name:"I diversamente agili"},
  {id:41,name:"frecce rosse"},
  {id:42,name:"Burkan"},
  {id:43,name:"La maggica"},
  {id:44,name:"Kinder Tetta e Latte"},
  {id:45,name:"Le bisce salterine"},
  {id:46,name:"Mascia e gli orsi"},
  {id:47,name:"I peones"},
  {id:48,name:"Volley essere un duro"},
  {id:49,name:"Campo uno sul campo due"},
  {id:50,name:"45 smalto bianco"},
  {id:51,name:"team magini"},
  {id:52,name:"Paris Saint Bagher"},
  {id:53,name:"No stress"},
  {id:54,name:"The charlatans"},
  {id:55,name:"Litfiga"},
  {id:56,name:"Le bimbe di Bona"},
  {id:57,name:"I belli di notte"},
  {id:58,name:"Pierre della Francesca"},
  {id:59,name:"A pelle i figli di Pollo"},
  {id:60,name:"Vercas"}
]

export default teams;


